local RUI = RetreatUITBC
if not RUI then return end

-- Class Aura Bar functional inventory. This stores only spell/aura/load metadata
-- used by RetreatUI's own WeakAura builders.
RUI.tbcAuraBarData = {
  DRUID = {
    {name="Nature's Swiftness (Active)",auras={17116},unit="player",debuffType="HELPFUL",loadSpell=17116},
    {name="Maul (Active)",spell=6807,loadSpell=6807,mode="queued"},
    {name="Barkskin (Active)",auras={22812},unit="player",debuffType="HELPFUL",loadSpell=22812},
    {name="Enrage (Active) - Druid",auras={5229},unit="player",debuffType="HELPFUL",loadSpell=5229},
    {name="Rejuvenation (Active)",auras={2091},unit="player",debuffType="HELPFUL",loadSpell=2091},
    {name="Regrowth (Active)",auras={8939},unit="player",debuffType="HELPFUL",loadSpell=8939},
    {name="Entangling Roots (Active)",auras={339},unit="multi",debuffType="HARMFUL",loadSpell=339},
    {name="Hibernation (Active)",auras={2637},unit="multi",debuffType="HARMFUL",loadSpell=2637},
    {name="Nature's Grasp (Active)",auras={16689},unit="player",debuffType="HELPFUL",loadSpell=16689},
    {name="Frenzied Regeneration (Active)",auras={22896},unit="player",debuffType="HELPFUL",loadSpell=22896},
    {name="Tiger's Fury (Active)",auras={9846},unit="player",debuffType="HELPFUL",loadSpell=9846},
    {name="Nature's Grace (Active)",auras={16880},unit="player",debuffType="HELPFUL"},
    {name="Clearcasting (Active) - Druid",auras={16870},unit="player",debuffType="HELPFUL"},
    {name="Lacerate (Active)",auras={33745},unit="target",debuffType="HARMFUL",loadSpell=33745},
  },
  HUNTER = {
    {name="Bestial Wrath (Active)",auras={19574},unit="player",debuffType="HELPFUL",loadSpell=19574},
    {name="Trueshot (Active)",auras={19506},unit="player",debuffType="HELPFUL",loadSpell=19506},
    {name="Quick Shots (Active)",auras={6150},unit="player",debuffType="HELPFUL"},
    {name="Feign Death (Active)",auras={5384},unit="player",debuffType="HELPFUL",loadSpell=5384},
    {name="Trap (Active)",auras={3355},unit="multi",debuffType="HARMFUL"},
    {name="Scare Beast (Active)",auras={1513},unit="multi",debuffType="HARMFUL",loadSpell=1513},
    {name="Flare (Active)",mode="combatlog",spellIds={1543},loadSpell=1543,duration=30},
  },
  MAGE = {
    {name="Icy Veins (Active)",auras={12472},unit="player",debuffType="HELPFUL",loadSpell=12472},
    {name="Ice Block (Active)",auras={45438},unit="player",debuffType="HELPFUL",loadSpell=45438},
    {name="Polymorph (Active)",auras={118},unit="multi",debuffType="HARMFUL",loadSpell=118},
    {name="Mana Shield (Active)",auras={1463},unit="player",debuffType="HELPFUL",loadSpell=1463},
    {name="Fire Vulnerability (Active)",auras={22959},unit="target",debuffType="HARMFUL"},
    {name="Winter's Chill (Active)",auras={28595},unit="target",debuffType="HARMFUL"},
    {name="Ignite (Active)",auras={12847},unit="target",debuffType="HARMFUL"},
    {name="Slow Fall (Active)",auras={130},unit="player",debuffType="HELPFUL",loadSpell=130},
    {name="Clearcasting (Active)",auras={12536},unit="player",debuffType="HELPFUL"},
    {name="Astral Power (Active)",auras={12042},unit="player",debuffType="HELPFUL",loadSpell=12042},
    {name="Ice Barrier (Active)",auras={11426},unit="player",debuffType="HELPFUL",loadSpell=11426},
    {name="Fire Ward (Active)",auras={10225},unit="player",debuffType="HELPFUL",loadSpell=10225},
    {name="Combustion (Active)",auras={28682},unit="player",debuffType="HELPFUL",loadSpell=28682},
    {name="Presence of Mind (Active)",auras={12043},unit="player",debuffType="HELPFUL",loadSpell=12043},
    {name="Arcane Blast (Active)",auras={30451},unit="player",debuffType="HELPFUL",loadSpell=30451},
  },
  PALADIN = {
    {name="Divine Favor (Active)",auras={20216},unit="player",debuffType="HELPFUL",loadSpell=20216},
    {name="Vengeance (Active)",auras={20059},unit="player",debuffType="HELPFUL"},
    {name="Seal of the Crusader (Active)",auras={20306},unit="player",debuffType="HELPFUL"},
    {name="Seal of Command (Active)",auras={27170},unit="player",debuffType="HELPFUL"},
    {name="Seal of the Righteousness (Active)",auras={20289},unit="player",debuffType="HELPFUL"},
    {name="Divine Shield (Active)",auras={1020},unit="player",debuffType="HELPFUL",loadSpell=1020},
    {name="Divine Protection (Active)",auras={498},unit="player",debuffType="HELPFUL",loadSpell=498},
    {name="Holy Shield (Active)",auras={20925},unit="player",debuffType="HELPFUL",loadSpell=20925},
    {name="Seal of Wisdom (Active)",auras={20351},unit="player",debuffType="HELPFUL"},
    {name="Seal of Justice (Active)",auras={20164},unit="player",debuffType="HELPFUL"},
    {name="Redoubt",auras={20137},unit="player",debuffType="HELPFUL"},
    {name="Reckoning",auras={20182},unit="player",debuffType="HELPFUL"},
  },
  PRIEST = {
    {name="Shadow Word: Pain",auras={589},unit="target",debuffType="HARMFUL",loadSpell=589},
    {name="Vampiric Touch",auras={34917},unit="target",debuffType="HARMFUL",loadSpell=34917},
    {name="Holy Fire",auras={14914},unit="target",debuffType="HARMFUL",loadSpell=14914},
    {name="Vampiric Embrace",auras={15286},unit="target",debuffType="HARMFUL",loadSpell=15286},
    {name="Shackle Undead (Active)",auras={9484},unit="multi",debuffType="HARMFUL",loadSpell=9484},
    {name="Mind Soothe (Active)",auras={10953},unit="multi",debuffType="HARMFUL",loadSpell=10953},
    {name="Shadowform (Active)",auras={15473},unit="player",debuffType="HELPFUL",loadSpell=15473},
    {name="Levitate (Active)",auras={1706},unit="player",debuffType="HELPFUL",loadSpell=1706},
    {name="Renew (Active)",auras={8362},unit="player",debuffType="HELPFUL",loadSpell=139},
    {name="Focused Casting (Active)",auras={14743},unit="player",debuffType="HELPFUL"},
    {name="Power Word: Shield (Active)",auras={10901},unit="player",debuffType="HELPFUL",loadSpell=17},
    {name="Inner Focus (Active)",auras={14751},unit="player",debuffType="HELPFUL",loadSpell=14751},
    {name="Spirit Tap (Active)",auras={15271},unit="player",debuffType="HELPFUL"},
  },
  ROGUE = {
    {name="Active • Sap",auras={11297},unit="multi",debuffType="HARMFUL",loadSpell=6770},
    {name="Evasion (Active)",auras={5277},unit="player",debuffType="HELPFUL",loadSpell=5277},
    {name="Riposte (Active)",spell=14251,loadSpell=14251,mode="usable"},
    {name="Vanish (Active)",auras={1856},unit="player",debuffType="HELPFUL",loadSpell=1856},
    {name="Blind (Active)",auras={2094},unit="multi",debuffType="HARMFUL",loadSpell=2094},
    {name="Adrenaline Rush (Active)",auras={13750},unit="player",debuffType="HELPFUL",loadSpell=13750},
    {name="Cold Blood (Active)",auras={14177},unit="player",debuffType="HELPFUL",loadSpell=14177},
    {name="Remorseless Attacks (Active)",auras={14149},unit="player",debuffType="HELPFUL"},
    {name="Blade Flurry (Active)",auras={13877},unit="player",debuffType="HELPFUL",loadSpell=13877},
  },
  SHAMAN = {
    {name="Lightning Shield (Active)",auras={10432},unit="player",debuffType="HELPFUL"},
    {name="Ancestral Fortitude (Active)",auras={16240},unit="player",debuffType="HELPFUL"},
    {name="Shamanistic Rage (Active)",auras={30823},unit="player",debuffType="HELPFUL",loadSpell=30823},
    {name="Shamanistic Focus (Active)",auras={43339},unit="player",debuffType="HELPFUL"},
    {name="Elemental Devastation (Active)",auras={29177},unit="player",debuffType="HELPFUL"},
    {name="Water Walking (Active)",auras={546},unit="player",debuffType="HELPFUL",loadSpell=546},
    {name="Eye of the Storm (Active)",auras={29063},unit="player",debuffType="HELPFUL"},
    {name="Stormstrike (Active)",auras={17364},unit="target",debuffType="HARMFUL",loadSpell=17364},
    {name="Clearcasting (Active) - Shaman",auras={16246,16164},unit="player",debuffType="HELPFUL"},
    {name="Flurry (Active) - Shaman",auras={16280},unit="player",debuffType="HELPFUL"},
    {name="Chromatic Infusion (Active)",auras={27675},unit="player",debuffType="HELPFUL"},
    {name="Elemental Focus (Active)",auras={16164},unit="player",debuffType="HELPFUL"},
  },
  WARLOCK = {
    {name="Banish (Active)",auras={710},unit="multi",debuffType="HARMFUL",loadSpell=710},
    {name="Nightfall (Active)",auras={17941,18095,18094},unit="player",debuffType="HELPFUL"},
    {name="Soul Siphon Execute (Active)",loadSpell=403511,mode="health",healthPercent=20},
    {name="Sacrifice (Active)",auras={19443},unit="player",debuffType="HELPFUL"},
    {name="Amplify Curse (Active)",auras={18288},unit="player",debuffType="HELPFUL",loadSpell=18288},
    {name="Fel Domination (Active)",auras={18708},unit="player",debuffType="HELPFUL",loadSpell=18708},
    {name="Shadow Ward (Active)",auras={6229},unit="player",debuffType="HELPFUL",loadSpell=6229},
    {name="Fel Armor (Active)",auras={28176},unit="player",debuffType="HELPFUL",loadSpell=28176},
    {name="Pyroclasm (Active)",auras={18093},unit="player",debuffType="HELPFUL"},
    {name="Demon Skin (Active)",auras={696},unit="player",debuffType="HELPFUL"},
    {name="Backlash (Active)",auras={34935},unit="player",debuffType="HELPFUL"},
  },
  WARRIOR = {
    {name="Heroic Strike (Active)",spell=78,loadSpell=78,mode="queued"},
    {name="Rampage (Active)",auras={30033},unit="player",debuffType="HELPFUL",loadSpell=30033},
    {name="Overpower (Active)",spell=7384,auras={426969},unit="player",debuffType="HELPFUL",loadSpell=7384,mode="usable"},
    {name="Shield Block (Active)",auras={2565},unit="player",debuffType="HELPFUL",loadSpell=2565},
    {name="Sunder Armor (Active)",auras={7405},unit="target",debuffType="HARMFUL",loadSpell=7386},
    {name="Enrage (Active)",auras={13046},unit="player",debuffType="HELPFUL"},
    {name="Flurry (Active)",auras={12970},unit="player",debuffType="HELPFUL"},
    {name="Recklessness (Active)",auras={1719},unit="player",debuffType="HELPFUL",loadSpell=1719},
    {name="Bloodrage (Active)",auras={29131},unit="player",debuffType="HELPFUL",loadSpell=2687},
    {name="Victory Rush (Active)",spell=34428,loadSpell=34428,mode="usable"},
    {name="Shield Wall (Active)",auras={871},unit="player",debuffType="HELPFUL",loadSpell=871},
    {name="Sweeping Strikes (Active)",auras={12292},unit="player",debuffType="HELPFUL",loadSpell=12328},
    {name="Bloodthirst (Active)",auras={23885},unit="player",debuffType="HELPFUL",loadSpell=23881},
    {name="Cleave (Active)",spell=20569,loadSpell=845,mode="queued"},
    {name="Battle Shout (Active)",auras={6673},unit="player",debuffType="HELPFUL",loadSpell=6673},
  },
}
